### ISSUE TITLE
Not clear where index.tar.gz goes

### ISSUE THREAD

**Issue by dkoslicki** [mahmudhera/smash_alternate_implementations#41]
The help menu for `index` says:
```
-s, --store-archive   Store a tar.gz archive of the index
```
which makes it look like a flag. However, using it as a flag `-s <other flags and arguments>` results in a literally named `.tar.gz` file in the same location as the second positional argument. Putting a full file name path `/path/to/index.tar.gz` results in an error of  `Maximum number of positional arguments exceeded, failed to parse '/scratch/dmk333_new/temp/Salmonella/data/indexed/'`
as seen in:
```
(base) dmk333@e5-cse-cbdmk02:/scratch/dmk333_new/temp/Salmonella/sourmash_alternate_implementations/bin$ ./index -t 128 -s /scratch/dmk333_new/temp/Salmonella/data/indexed/whole_database_scaled_100.tar.gz /scratch/dmk333_new/temp/Salmonella/data/uncompressed_individual_paths.txt /scratch/dmk333_new/temp/Salmonella/data/indexed/
Maximum number of positional arguments exceeded, failed to parse '/scratch/dmk333_new/temp/Salmonella/data/indexed/'
```
Perhaps it should be made clear that `-s` expects a base name, and it will be stored in the same location as the second positional argument.

**Comment by mahmudhera** [comment]
Could you please checkout the "fix-archive-path" branch, build the binaries, and check if `--help` explains things okay?

Currently it shows:

```
Positional arguments:
  filelist_sketches     The path to the file containing the paths to the sketches [required]
  index_directory_name  The directory where the index will be stored (must be a directory) [required]

Optional arguments:
  -h, --help            shows help message and exits 
  -v, --version         prints version information and exits 
  -t, --threads         The number of threads to use [nargs=0..1] [default: 1]
  -n, --num-hashtables  The number of hash tables to use [nargs=0..1] [default: 4096]
  -s, --store-archive   Store a tar.gz archive of the index 
  -a, --archive-name    The name of the archive (will be discarded if store-archive is false) [nargs=0..1] [default: "index.tar.gz"]
  -f, --force-write     Force write the index to the directory 
```

The intended behavior is as follows:

- `index_directory_name` is a positional argument, and **must** be a directory (now mentioned in `--help`)
- `-s` is indeed a flag
- `-a` (newly added) will accept the desired tar.gz archive name, works with absolute/relative path. This is unused if `-s` is absent

Let me know if you find these changes, and if these changes make the behavior more understandable. If not, we can revise again before doing a PR into main.

**Comment by dkoslicki** [comment]
Thanks! I've checked it and indeed that clarifies it
